### ISSUE TITLE
UI and mouse do not match aligned movement

### ISSUE THREAD

**Issue by psoizzac** [Shirk/XIPivot#16]
as the header suggests, the mouse has a invisibile mouse next to it, the mouse displayed will not be recognized , only the invisible one. as you move the mouse both mouses follow. Can't interact with UI to click buttons or tabs.

**Comment by clanofartisans** [comment]
If you're talking about the Pivot UI that comes up when you type `/pivot`, I suspect you are playing in Windowed mode which is thrown off a bit depending on the size of the window's title bar.

**Comment by HealsCodes** [comment]
Not related to anything pivot does - please file a big on the Ashitav4 repo after making sure it's not related to your XI settings.
