### ISSUE TITLE
Add explanation for how the cache settings work

### ISSUE THREAD

**Issue by gammaleak** [Shirk/XIPivot#3]
I wonder if you could add an explanation somewhere in the release readme or on the main page of the project about how the cache settings work in the configuration xml.

There appear to be three settings:
- cache_size
- cache_max_age
- cache_enabled

The last one is "false" by default. I assume "size" is in MB, but that's just an assumption. I also assume "max age" is in seconds, but that would mean the default is only ten minutes which seems short-ish.

In any case, an official explanation would be useful along with recommendations about how or when this feature should be used.

Thank you for some great software here.

**Comment by HealsCodes** [comment]
Thanks for pointing out the missing documentation (I thought I had written it down..).
MemCache is mostly meant to be configured using the in-game UI which labels the parameters more clearly,
but I also included a description in the respective README for the Ashita v3 an v4 version of pivot.
